export const mockFollowList = {
  code: 0,
  message: '0',
  ttl: 1,
  data: {
    list: [
      {
        mid: 1682901522,
        attribute: 0,
        mtime: 1684216940,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'CEST斗牌立直赛',
        face: 'https://i0.hdslb.com/bfs/face/7e12fe7fcaab9caf5efadddf458389bdfd564457.jpg',
        sign: '精彩复盘，每天下午14:00一个半庄\n想参加的宝宝资料小助手～',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1701878400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 94652321,
        attribute: 0,
        mtime: 1684138450,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'ゆうく',
        face: 'https://i2.hdslb.com/bfs/face/5bcfa626ac1b58e3e6b0c5b8f9da591e1e556e66.jpg',
        sign: '计算机博士在读 三级笔译 日麻爱好者',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1703952000000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 353240497,
        attribute: 0,
        mtime: 1684120742,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '雀魂麻将majsoul',
        face: 'https://i1.hdslb.com/bfs/face/7c1c1b2b3e7b7ab4708de8331cc9babeef65bf43.jpg',
        sign: '最有爱的二次元麻将游戏雀魂麻将，快来体验一下吧',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili 知名游戏UP主',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1709654400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 178648,
        attribute: 0,
        mtime: 1684120738,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'Mint_Choco_Late',
        face: 'https://i1.hdslb.com/bfs/face/25e6e32e2ec249c96ab875f508f1a4ea73f4ade6.jpg',
        sign: '一块乖巧可爱又美丽的薄荷巧克力。 只打三麻 / 樱花骑士团粉丝 / 天凤ID MintCoco',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1726329600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 3493265252812816,
        attribute: 0,
        mtime: 1683979150,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '小琦讲麻将',
        face: 'https://i1.hdslb.com/bfs/face/6097fe2d0f31187f3dd72b693a310514000d8441.jpg',
        sign: '2022年成立麻将AI学院，利用人工智能突破传统麻将边界2018年恒星赛国际麻将竞技一等奖\n2016年川麻杯四川麻将青年赛二等奖',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 438435,
        attribute: 0,
        mtime: 1683875636,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'CFv呆呆兽',
        face: 'https://i0.hdslb.com/bfs/face/4cd0af73783547b2f69a5c9a317752aff1cd6be5.jpg',
        sign: '雀魂四麻魂天Lv5+三麻魂天Lv13 天凤四麻八段/三麻九段 QQ三群：616839575',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1727625600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 388569543,
        attribute: 0,
        mtime: 1683510261,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '雀姬麻将',
        face: 'https://i0.hdslb.com/bfs/face/dd1a2b0f5529f24c8c9e8aec9666590c88d91aeb.jpg',
        sign: '牌逢对手，即刻开局！',
        face_nft: 0,
        official_verify: {
          type: 1,
          desc: '雀姬麻将官方账号',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1678291200000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1443131643,
        attribute: 0,
        mtime: 1682496422,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '张博达-',
        face: 'https://i0.hdslb.com/bfs/face/81d7520cf7fef661979ae963c03ebe17c2556750.jpg',
        sign: '祝我的粉丝们每天开心、健康、快乐！',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1700409600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 447317111,
        attribute: 0,
        mtime: 1682243309,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'Meetfood觅食',
        face: 'https://i2.hdslb.com/bfs/face/bea5c769459bddb4b955c19ce4e4dc3d8b46f8ea.jpg',
        sign: '海外美食测评，美食的背后是文化和故事',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili 知名美食UP主',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1712764800000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 7823848,
        attribute: 0,
        mtime: 1682231833,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '早睡的小羊',
        face: 'https://i1.hdslb.com/bfs/face/df3a856782eaf97556b08f063fab7ec5ff53e0ba.jpg',
        sign: '声音像懒羊羊的王者主播\n每晚B站直播白天偶尔在每周二休息\n群：659163010 巅峰国标：KoiSusu备注\n人生苦短，及时行乐，多做多学',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1717084800000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1327099449,
        attribute: 0,
        mtime: 1681402707,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '小叮当爱睡觉助眠',
        face: 'https://i0.hdslb.com/bfs/face/c6c133808887834642e6b3fbaa8098ce8f20207a.jpg',
        sign: '欢迎来到小叮当助眠直播间\n帮助您更好的睡眠\n直播时间：每天晚9点～中午2点，记得来哦\n感谢大家聆听，感谢关注～嘻嘻',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 690886435,
        attribute: 0,
        mtime: 1681279099,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'YouTube助眠收藏',
        face: 'https://i1.hdslb.com/bfs/face/fd560693aebb0df394e232226afb8fe7ceed6f9b.jpg',
        sign: '随缘更新',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1689177600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 929197,
        attribute: 0,
        mtime: 1681279033,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '甜隐君子',
        face: 'https://i1.hdslb.com/bfs/face/3b945a1c7396d92b97d27ffb7c88604c23d8d3c7.jpg',
        sign: '日语个人烤肉；想带给大家好看好玩的东西~',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1702483200000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 647193094,
        attribute: 0,
        mtime: 1680418037,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '装扮小姐姐',
        face: 'https://i1.hdslb.com/bfs/face/baa15280b6157891427323fab5fbe3e3b42010cf.jpg',
        sign: '₍ᐢ⸝⸝› ̫ ‹⸝⸝ᐢ₎发布各种个性装扮的最新资讯，不定期发放福利，近期私信较多可能会漏，有反馈和建议欢迎@我w',
        face_nft: 0,
        official_verify: {
          type: 1,
          desc: '个性装扮官方账号',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1696089600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1221164058,
        attribute: 0,
        mtime: 1680418037,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '狼队王者荣耀分部',
        face: 'https://i0.hdslb.com/bfs/face/135e298f91ab0733f0d7884b46c89c97f78333df.jpg',
        sign: '来啦？',
        face_nft: 0,
        official_verify: {
          type: 1,
          desc: '狼队王者荣耀分部官方账号',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1708704000000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1425239276,
        attribute: 0,
        mtime: 1680418037,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '哔哩哔哩数字周边',
        face: 'http://i0.hdslb.com/bfs/baselabs/d48107584bb1a28c0898be2954133157dd26d3f4.jpg',
        sign: '数字周边和数字藏品就找鸽！哔哩哔哩 ( ゜- ゜)つロ干杯~ ',
        face_nft: 1,
        official_verify: {
          type: 1,
          desc: '哔哩哔哩数字周边官方账号',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1685894400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon:
          'https://i0.hdslb.com/bfs/activity-plat/static/20220506/334553dd7c506a92b88eaf4d59ac8b4d/j8AeXAkEul.gif',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 369560257,
        attribute: 0,
        mtime: 1680368482,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '打工战士阿万音_',
        face: 'https://i1.hdslb.com/bfs/face/d88f397ce52459432be9666a1bb2d3b3a987b39f.jpg',
        sign: '编辑个性签名',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1684252800000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '大会员',
            label_theme: 'vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 328538733,
        attribute: 0,
        mtime: 1680367953,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '老耗游戏',
        face: 'https://i0.hdslb.com/bfs/face/9d67c8d772a75e877e6417d5fcc034606ca46d79.jpg',
        sign: '商务合作：XKYCY888（备注老耗) 老耗游戏本人，有坑作的可以找我哟  Q群：976812364',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili 知名游戏UP主',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1685894400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '大会员',
            label_theme: 'vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1636194007,
        attribute: 0,
        mtime: 1680259659,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '阿鱼爱学习本人',
        face: 'https://i1.hdslb.com/bfs/face/ecbe23ea9f24698621175ba7e861a2ca56e43ff8.jpg',
        sign: '书荒可以看我，我给自己的定位是图书种草而不是解读、不专业只是读者而已，开心会做长视频唷～\n有个公众号：阿鱼唠嗑。\n商务：yhcluo',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: '阿鱼爱学习官方账号',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1681228800000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 30707134,
        attribute: 0,
        mtime: 1680199095,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '马格南DD',
        face: 'https://i1.hdslb.com/bfs/face/64e74a6f8baf7506150a5838d3e4b27a0e950d43.jpg',
        sign: '这里是马格南本人，一个把纸牌玩到极致的男护士\n感谢各位铁子的点赞 salute!!!\n合作v：MGN536',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: '等等官方账号',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1700236800000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 452060800,
        attribute: 0,
        mtime: 1680197388,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '空想家欧文',
        face: 'https://i1.hdslb.com/bfs/face/b981e8922ecc62189bf89c8b5802c4a2d3837651.jpg',
        sign: '',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1691078400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 484322035,
        attribute: 0,
        mtime: 1680063738,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'AIChannel中国绊爱',
        face: 'https://i1.hdslb.com/bfs/face/77a58d8b3a167f989f842cda550e7230ef4cad0a.jpg',
        sign: '嗨多磨！我是爱哥！商务合作请找@哎咿多工作室 合作邮箱：business@a1duo.com粉丝三群：175060574',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: '中国绊爱官方账号',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1710000000000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 3094,
        attribute: 0,
        mtime: 1679503360,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'ゆっくり',
        face: 'http://i1.hdslb.com/bfs/face/bb2ca55b596cc4205259fc83cfc919ed367199bd.gif',
        sign: '',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 314387912,
        attribute: 0,
        mtime: 1679443331,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'YouTube助眠频道',
        face: 'https://i2.hdslb.com/bfs/face/f6df48dc867888266a50c890d5ec5756cffe2035.jpg',
        sign: '专注最新高质量的YouTube视频搬运+日更助眠系列视频！【PS:喜欢的话可以持续关注哦( °◅° )】',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1581609600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 65372185,
        attribute: 0,
        mtime: 1679193753,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '词穷-马超人柱力',
        face: 'https://i1.hdslb.com/bfs/face/e541ea97827d18db81a43c6dbe66c4a3ead73d0d.jpg',
        sign: '战斗の鱼：词穷\ns30巅峰周定榜第一第六\n宇宙第一24085战力马超',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1710259200000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 697139341,
        attribute: 0,
        mtime: 1679076223,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '七彩猫-国服王昭君',
        face: 'https://i1.hdslb.com/bfs/face/456182168d1743fcd58cbb35d519cb60dfc285b7.jpg',
        sign: '培丸：im669886（国服技术）\n上分q：2907595284\n粉丝群709451536\n粉丝群854085535',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili 知名游戏UP主、直播高能主播',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1709740800000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 317795329,
        attribute: 0,
        mtime: 1678810876,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '成都雪霁电竞',
        face: 'https://i1.hdslb.com/bfs/face/9b1e5a24640efb648f20177aa2b55da5be197876.jpg',
        sign: '电竞培训咨询v:15583385391\n私人v:limingxueji1',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1684857600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '大会员',
            label_theme: 'vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 632171719,
        attribute: 0,
        mtime: 1678805775,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '紫贝儿official',
        face: 'https://i1.hdslb.com/bfs/face/6ccafbfe0aeff0f57ac6408102cbf627d3728581.jpg',
        sign: '个人势美食Vup  来吃顿好的！直播时间：下午15：00-17：00；晚上：20：00-22：00（不授权录播）',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili直播高能主播',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1702310400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1621562316,
        attribute: 0,
        mtime: 1678723323,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '杰出ACG',
        face: 'https://i0.hdslb.com/bfs/face/4cb84f170feddbfdd131122f0ab42c44e5cf98b8.jpg',
        sign: '交流群 334792156 公众号 杰出ACG（进去跳转一次公众号防炸）',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 2077733317,
        attribute: 0,
        mtime: 1678646409,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '烛不遥',
        face: 'https://i1.hdslb.com/bfs/face/b03b5ee96b7b15327d3562fca03e725d620ffa8f.jpg',
        sign: '本是神庙中的小蜡烛！目前在凡间的烧烤店打工！养成系国风歌势！歌同步更新在网易云【烛不遥】(备注：小蜡烛的火焰有一定攻击性，请勿开过分的玩笑)',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1706457600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1569685991,
        attribute: 0,
        mtime: 1678350124,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '船长电影解说',
        face: 'https://i2.hdslb.com/bfs/face/80f33842c62770b4520950fb3f42f9c73b488106.jpg',
        sign: '你只管听我给你讲故事就完事了~嘿嘿...\nV：JLK555666',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili 知名影视UP主',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 472864207,
        attribute: 0,
        mtime: 1678061655,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'AG小兽',
        face: 'https://i1.hdslb.com/bfs/face/f236af362a9ce3dfbf27487f1d9c41acfc6ecf6a.jpg',
        sign: '复最细的盘，挨最狠的骂。\nKPL职业教练/解说1v1私教课：agedu1\n成都AG超玩会王者荣耀项目教练\n2018年KPL秋季赛最佳打野',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1718553600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 43031383,
        attribute: 0,
        mtime: 1678022191,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '小灵泡芙',
        face: 'https://i1.hdslb.com/bfs/face/73a0c681bf18e852bde5841c266ab61ced1f38b6.jpg',
        sign: '11国服女中单小灵泡芙期待你的关注   ',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1126149937,
        attribute: 0,
        mtime: 1677872402,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '顾笙游戏解说',
        face: 'https://i1.hdslb.com/bfs/face/c520abcca19492d444879c7e1ea147621f1a1c7c.jpg',
        sign: '因为热爱所以坚持！',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 173454152,
        attribute: 0,
        mtime: 1677819674,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '坐大狗的白狼',
        face: 'https://i2.hdslb.com/bfs/face/1b8180644f0d99acb63b0282644d6f689ca392e4.jpg',
        sign: '废物教练，也有可能是个数据分析\n群号786828988\n可以来一起聊游戏理解和bp哦',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1687363200000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 39998728,
        attribute: 0,
        mtime: 1677462449,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '缘分浅于止肩',
        face: 'https://i1.hdslb.com/bfs/face/234c36e29028daf799344f053594169c32f8ec39.jpg',
        sign: '人生不如意之事七八九，苦事；终归还能与人言一二三，幸事。',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1698595200000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 3380239,
        attribute: 0,
        mtime: 1677174705,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '神奇的老皮VFX',
        face: 'http://i1.hdslb.com/bfs/face/e7c191e9be6764107415069b36f7d9564f149c86.gif',
        sign: '中二特效，最皮团队！  合作加wx: amazing_lp',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: ' bilibili 2019百大UP主、知名UP主',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1696694400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 558372320,
        attribute: 0,
        mtime: 1677061977,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '教书李白珍恩夫',
        face: 'https://i2.hdslb.com/bfs/face/a2c75fc36a2ab8a856827bc95b8ee7049dbd4edc.jpg',
        sign: '本人任意英雄上星巅峰fxyzz159753\n群634613638\n直播时间：19：00—23：30\n',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 3461581799164761,
        attribute: 0,
        mtime: 1677058357,
        tag: [],
        special: 0,
        contract_info: {},
        uname: 'liqr_music',
        face: 'https://i0.hdslb.com/bfs/face/9e301aa4debdaee0648d9986bb646e8502137d7b.jpg',
        sign: '我通過反複試驗製作音樂。\nTwitter：https://twitter.com/LQRmusic',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 177309171,
        attribute: 0,
        mtime: 1676696105,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '全自动手花式',
        face: 'https://i0.hdslb.com/bfs/face/d6b338608878f8aba2981d7d608fc6cb473a352f.jpg',
        sign: 'B站直播\n全网独家玄学混分\n商务v：ZJ82544\n上分v：lxg15314203674\n直播时间12到2点\n晚上7.30到11.30\n\n\n',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili直播高能主播',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1693238400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 179754017,
        attribute: 0,
        mtime: 1676316155,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '石润森',
        face: 'https://i2.hdslb.com/bfs/face/a90f68a425bdc22fe0ff6bdab1b73cc625e49bd9.jpg',
        sign: '一起变成光！',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1719244800000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 666662214,
        attribute: 0,
        mtime: 1676315205,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '奥特博物馆',
        face: 'http://i0.hdslb.com/bfs/face/23abcb5c8dec2d0f4e40d391f43c801edd83d23a.jpg',
        sign: '同步视频中...\n一般不出意外的话，我努力周三到周六更新哈',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili 知名动漫UP主',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1618761600000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 397184284,
        attribute: 0,
        mtime: 1676217222,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '说动漫的雷欧',
        face: 'https://i1.hdslb.com/bfs/face/a9971588dd028d1a0bbed385785de7eb59fdc7e0.jpg',
        sign: '虽然配音是机器\n但作品均为原创\n一直保持着那颗热爱特摄的心\n目前更新《迪迦》《盖亚》深度解析！\n',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1684598400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '大会员',
            label_theme: 'vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 1098173832,
        attribute: 0,
        mtime: 1676092286,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '宋云生-',
        face: 'https://i0.hdslb.com/bfs/face/fca17ec3de184b038620eca0043c57d282c58ba9.jpg',
        sign: '一个高冷的美男子罢了',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1697472000000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 629545145,
        attribute: 0,
        mtime: 1676078168,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '你的圈圈儿',
        face: 'https://i2.hdslb.com/bfs/face/4f41fff7e664f145e6ff2b7a583140314acb0e99.jpg',
        sign: '虎-呀直播间：297376. 粉丝群:107808133',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1701446400000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 477761024,
        attribute: 0,
        mtime: 1676048202,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '觅长生官方',
        face: 'http://i2.hdslb.com/bfs/face/a07ac10994aa65a18720d1559a484f9d54584f0e.jpg',
        sign: '觅长生官方账号',
        face_nft: 0,
        official_verify: {
          type: 1,
          desc: '觅长生官方账号',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 655181,
        attribute: 0,
        mtime: 1676037771,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '少年霜',
        face: 'https://i2.hdslb.com/bfs/face/c88e244a21b43e63edbc55132f9a9aa04454af42.jpg',
        sign: '你的家养少主，请管家用心培育，不可食用×  少主府在：796458367',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili 知名音乐UP主',
        },
        vip: {
          vipType: 2,
          vipDueDate: 1736179200000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 1,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '年度大会员',
            label_theme: 'annual_vip',
            text_color: '#FFFFFF',
            bg_style: 1,
            bg_color: '#FB7299',
            border_color: '',
          },
          avatar_subscript: 1,
          nickname_color: '#FB7299',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 3493124710075142,
        attribute: 0,
        mtime: 1675934489,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '小七真的C百段中路',
        face: 'https://i2.hdslb.com/bfs/face/4d3be04e0a84b7dd4b3dc3806af546df95fb2f3e.jpg',
        sign: '',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 104414985,
        attribute: 0,
        mtime: 1675792444,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '幸运观众10086',
        face: 'https://i0.hdslb.com/bfs/face/850714bbad21799b57a8664b57b0dd1927e67527.jpg',
        sign: '群539948360\n',
        face_nft: 0,
        official_verify: {
          type: -1,
          desc: '',
        },
        vip: {
          vipType: 0,
          vipDueDate: 0,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
      {
        mid: 2022118343,
        attribute: 0,
        mtime: 1675621464,
        tag: [],
        special: 0,
        contract_info: {},
        uname: '无敌老墨言',
        face: 'https://i2.hdslb.com/bfs/face/d579dbcab4db71630b91138df5fe12d7e79a0534.jpg',
        sign: '猫猫猎手已登场！幽灵猎物已登场！\n我是墨言，喜欢我的视频就点赞关注支持一下喵！\nQQ水友粉丝群：543324568。',
        face_nft: 0,
        official_verify: {
          type: 0,
          desc: 'bilibili 知名游戏UP主',
        },
        vip: {
          vipType: 1,
          vipDueDate: 1626451200000,
          dueRemark: '',
          accessStatus: 0,
          vipStatus: 0,
          vipStatusWarn: '',
          themeType: 0,
          label: {
            path: '',
            text: '',
            label_theme: '',
            text_color: '',
            bg_style: 0,
            bg_color: '',
            border_color: '',
          },
          avatar_subscript: 0,
          nickname_color: '',
          avatar_subscript_url: '',
        },
        nft_icon: '',
        rec_reason: '',
        track_id: '',
      },
    ],
    re_version: 0,
    total: 1026,
  },
};
